#!/bin/bash
#
# Program: Setup a vagrant env
# History: 2017/1/19 Kyle.b Release

source ./scripts/func-vars.sh
set -eu

: ${MASTERS:="1"}
: ${NODES:="2"}
: ${CPU:="1"}
: ${MEMORY:="1024"}
: ${ETH:="enp0s8"}
: ${PROVIDER:="virtualbox"}
: ${OS_IMAGE:="ubuntu16"}

function usage() {
  echo -e "Usage : setup-vagrant [options]\n"
  echo " -b|--boss        Set number of master."
  echo " -n|--node        Set number of node."
  echo " -c|--cpu         Set number of cores per vm."
  echo " -m|--memory      Set memory size per vm."
  echo " -p|--provider    Set virtual machine provider(virtualbox, libvirt)."
  echo " -o|--os-image    Set virtual machine operation system(ubuntu16, centos7)."
  echo " -i|--interface   Set the network bind interface."
  exit 1
}

[ ${#} -gt 0 ] && [ ${1} == "-h" ] && usage

while [ ${#} -gt 0 ]; do
  case "${1}" in
      -b|--boss) isnum ${2}; MASTERS=${2}; shift;;
      -n|--node) isnum ${2}; NODES=${2}; shift;;
      -c|--cpu) isnum ${2}; CPU=${2}; shift;;
      -m|--memory) isnum ${2}; MEMORY=${2}; shift;;
      -i|--interface) ETH=${2}; shift;;
      -o|--os-image) OS_IMAGE=${2}; shift;;
      -p|--provider) PROVIDER=${2}; shift;;
      *) usage; break;;
  esac
  shift
done

echo "Cluster Size: ${MASTERS} master, ${NODES} node."
echo "     VM Size: ${CPU} vCPU, ${MEMORY} MB"
echo "     VM Info: ${OS_IMAGE}, ${PROVIDER}"
read -p "Start deploying?(y): " check && [ "${check}" != "y" ] && exit 1

vagrant_config "master_count" ${MASTERS}
vagrant_config "node_count" ${NODES}
vagrant_config "system_memory" ${MEMORY}
vagrant_config "system_vcpus" ${CPU}

update_vars
if [ ${NETWORK} == 'flannel' ]; then
  role_config "cni_opts:.*" "cni_opts: --iface=${ETH}" ${GROUP_VARS_PATH}
elif [ ${NETWORK} == 'calico' ]; then
  role_config "cni_opts:.*" "cni_opts: interface=${ETH}" ${GROUP_VARS_PATH}
fi

role_config "etcd_interface: \"\"" "etcd_interface: ${ETH}" ${ETCD_DEFAULT_PATH}
role_config "node_interface: \"\"" "node_interface: ${ETH}" ${NODE_DEFAULT_PATH}
role_config "vip_interface:.*" "vip_interface: ${ETH}" ${VIP_DEFAULT_PATH}
role_config "${SUBNET}.[0-9]*" "${SUBNET}.9" ${GROUP_VARS_PATH}
role_config "HOSTS=\".*\"" "HOSTS=\"${HOSTS}\"" ${INITIAL_SCRIPT_PATH}
role_config "${MASTER_PREFIX}[0-9]*" "${MASTER_PREFIX}${MASTER_COUNT}" ${INITIAL_SCRIPT_PATH}

# Create inventory and hosts
set_inventory
set_hosts

# Run vagrant
export OS_IMAGE=${OS_IMAGE}
vagrant up --provider ${PROVIDER}
