---

- name: Delete docker0 interface
  ignore_errors: True
  command: ip link delete docker0

- name: Enable and restart Docker engine
  systemd:
    name: docker
    daemon_reload: yes
    state: restarted
    enabled: yes
  register: started_docker

- name: Wait for repository server start
  when: repos_mode
  uri:
    url: "{{ repos_url }}"
    validate_certs: no
  register: result
  until: result.status == 200 or result.status == 401
  retries: 10
  delay: 5
  delegate_to: "{{ groups['repos'][0] }}"
  run_once: true
