{
 "title": "K8s / Node(GPU)",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "Instance",
    "query": "label_values(node_uname_info, instance)"
   },
   {
    "name": "Node_Name",
    "query": "label_values(node_uname_info{instance=~\"$Instance:9100\"}, nodename)"
   }
  ]
 },
 "panels": [
  {
   "title": "已使用GPU張數",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"nvidia_com_gpu\", node=\"$Node_Name\"}) OR vector(0)"
    }
   ]
  },
  {
   "title": "GPU總張數",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "nvidia_gpu_num_devices{instance=\"$Instance:9445\"}"
    }
   ]
  },
  {
   "title": "CPU使用率(%)",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 3 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(sum by (cpu) (irate(node_cpu{job=\"node-exporter\", mode!=\"idle\", instance=\"$Instance:9100\"}[2m]))) * 100"
    }
   ]
  },
  {
   "title": "記憶體使用率(%)",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 3 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(((node_memory_MemTotal{job=\"node-exporter\", instance=\"$Instance:9100\"} - node_memory_MemFree{job=\"node-exporter\", instance=\"$Instance:9100\"} - node_memory_Buffers{job=\"node-exporter\", instance= \"$Instance:9100\"} - node_memory_Cached{job=\"node-exporter\", instance=\"$Instance:9100\"}) / node_memory_MemTotal{job=\"node-exporter\", instance=\"$Instance:9100\"}) * 100)"
    }
   ]
  },
  {
   "title": "GPU使用率",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nvidia_gpu_duty_cycle{instance=\"$Instance:9445\"}",
     "legendFormat": "{{name}}, {{uuid}}"
    }
   ]
  },
  {
   "title": "GPU記憶體使用量（byte）",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nvidia_gpu_memory_used_bytes{instance=\"$Instance:9445\"}",
     "legendFormat": "{{name}}, {{uuid}}"
    }
   ]
  },
  {
   "title": "GPU Power使用量（mW）",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nvidia_gpu_power_usage_milliwatts{instance=\"$Instance:9445\"}",
     "legendFormat": "{{name}}, {{uuid}}"
    }
   ]
  },
  {
   "title": "GPU溫度",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nvidia_gpu_temperature_celsius{instance=\"$Instance:9445\"}",
     "legendFormat": "{{name}}, {{uuid}}"
    }
   ]
  }
 ]
}