#!/bin/bash
#
# Program: Reset all config
# History: 2017/1/25 Kyle.b Release

source ./tools/func-vars
source ./tools/.cache
set -eu

ETH=${1:-"enp0s8"}

role_config "network:.*" "network: calico" ${GROUP_VARS_PATH}
role_config "cni_iface:.*" "cni_iface: \"\"" ${GROUP_VARS_PATH}
role_config "etcd_iface:.*" "etcd_iface: \"\"" ${GROUP_VARS_PATH}
role_config "keepalived_vip_interface:.*" "keepalived_vip_interface: \"{{ ansible_default_ipv4.interface }}\"" ${GROUP_VARS_PATH}
role_config "${SUBNET}.[0-9]*" "${SUBNET}.9" ${GROUP_VARS_PATH}

rm -rf inventory hosts
vagrant destroy -f
