#!/bin/bash
#
# Program: Setup a vagrant env
# History: 2017/1/19 Kyle.b Release

source ./tools/func-vars

set -eu

: ${MASTERS:="1"}
: ${NODES:="2"}
: ${CPU:="1"}
: ${MEMORY:="1024"}
: ${ETH:="enp0s8"}
: ${CNI_PLUGIN:="calico"}
: ${PROVIDER:="virtualbox"}
: ${OS_IMAGE:="ubuntu16"}
: ${FORCE:="false"}

function usage() {
  echo -e "Usage : setup-vagrant [options]\n"
  echo " -b|--boss        Number of master."
  echo " -w|--worker      Number of worker."
  echo " -c|--cpu         Number of cores per vm."
  echo " -m|--memory      Memory size per vm."
  echo " -p|--provider    Virtual machine provider(virtualbox, libvirt)."
  echo " -o|--os-image    Virtual machine operation system(ubuntu16, centos7)."
  echo " -i|--interface   Network bind interface."
  echo " -n|--network     Container Network plugin."
  echo " -f|--force       Force deployment."
  exit 1
}

[ ${#} -gt 0 ] && [ ${1} == "-h" ] && usage

while [ ${#} -gt 0 ]; do
  case "${1}" in
      -b|--boss)   isnum ${2}; export MASTERS=${2}; shift;;
      -w|--worker) isnum ${2}; export NODES=${2}; shift;;
      -c|--cpu)    isnum ${2}; export CPU=${2}; shift;;
      -m|--memory) isnum ${2}; export MEMORY=${2}; shift;;
      -i|--interface) export ETH=${2}; shift;;
      -o|--os-image)  export OS_IMAGE=${2}; shift;;
      -p|--provider)  export PROVIDER=${2}; shift;;
      -n|--network)  export CNI_PLUGIN=${2}; shift;;
      -f|--force)    export FORCE=${2}; shift;;
      *) usage; break;;
  esac
  shift
done

echo "Cluster Size: ${MASTERS} master, ${NODES} worker."
echo "     VM Size: ${CPU} vCPU, ${MEMORY} MB"
echo "     VM Info: ${OS_IMAGE}, ${PROVIDER}"
echo "         CNI: ${CNI_PLUGIN}"
if [ ${FORCE} == "false" ]; then
  read -p "Start deploying?(y): " check && [ "${check}" != "y" ] && exit 1
fi

vagrant_config "master_count.*" "master_count = ${MASTERS}"
vagrant_config "node_count.*" "node_count = ${NODES}"
vagrant_config "system_vcpus.*" "system_vcpus = ${CPU}"
vagrant_config "system_memory.*" "system_memory = ${MEMORY}"

check_cni ${CNI_PLUGIN}

role_config "network:.*" "network: ${CNI_PLUGIN}" ${GROUP_VARS_PATH}
if [ ${CNI_PLUGIN} == 'flannel' ]; then
  role_config "cni_iface:.*" "cni_iface: --iface=${ETH}" ${GROUP_VARS_PATH}
elif [ ${CNI_PLUGIN} == 'calico' ]; then
  role_config "cni_iface:.*" "cni_iface: interface=${ETH}" ${GROUP_VARS_PATH}
elif [ ${CNI_PLUGIN} == 'canal' ]; then
  role_config "cni_iface:.*" "cni_iface: ${ETH}" ${GROUP_VARS_PATH}
elif [[ ${CNI_PLUGIN} == 'weave' || ${CNI_PLUGIN} == 'router' ]]; then
  role_config "cni_iface:.*" "cni_iface: \"\"" ${GROUP_VARS_PATH}
fi

role_config "etcd_iface: \"\"" "etcd_iface: ${ETH}" ${GROUP_VARS_PATH}
role_config "keepalived_vip_interface:.*" "keepalived_vip_interface: ${ETH}" ${GROUP_VARS_PATH}
role_config "${SUBNET}.[0-9]*" "${SUBNET}.9" ${GROUP_VARS_PATH}

# Create inventory and hosts
set_inventory
set_hosts

vagrant up
